apiVersion: v1
kind: Service
metadata:
  namespace: todo
  labels:
    app: microservice-app-example
    service: auth-api
  name: auth-api
spec:
  ports:
  - port: 8081
  selector:
    service: auth-api