apiVersion: v1
kind: Service
metadata:
  namespace: todo
  labels:
    app: microservice-app-example
    service: redis-queue
  name: redis-queue
spec:
  ports:
  - port: 6379
  selector:
    service: redis-queue